- .gitignore
Ignoring terraform, venvs, envs, keys
> Standard gitignore

- schema/connect.sh
- schema/schema.sql
Here is the schema definition and the shell script to connect to the database
> connection shell and schema

- .github/workflows/lint.yaml
Workflow actions for testing for quality and errors
> Pylint and Pytest workflows

- schema/seed_master_data.py
- schema/test_seed_master_data.py
Fixed the test to correctly use region for region map
> fixed tests

- archive/lambda_function/ecr-archive-lambda-push.sh
bash script for pushing the lambda image to an ECR.
> bash script

- archive/lambda_function/sample_data.sql
- archive/lambda_function/to_csv.py
> added more columns + row names to csv

- archive/lambda_function/test_to_csv.py
- archive/lambda_function/to_csv.py
> written test for to_csv.py

- pipeline/test_transformation.py
- pipeline/transform.py
Should finish issue #11 
Transforms and validates the API data
Fully tested(ish)
> Transforming data

- pipeline/pipeline.py
- pipeline/requirements.txt
I can now make multiple API calls in parallel speeding up the program.
> Asynchronous API calls

- archive/lambda_function/archive_pipeline.py
- archive/terraform/main.tf
Updated to take new schema into account
> Archive lambda

- pipeline/Dockerfile
- pipeline/pipeline.py
- pipeline/pipeline_ecr_push.sh
- pipeline/requirements.txt
added dockerfile and successfully dockerised pipeline script
> Pipeline lambda

- archive/terraform/main.tf
added SCHEMA_NAME
closes #88 
closes #83.
> added schema name

- pipeline/terraform/lambda_pipeline.tf
conforms to the name of the existing ECR, and adds a necessary variable
> small name changes

- archive/lambda_function/archive_pipeline.py
- dashboard/dashboard.py
should refresh the table after every usage as to not duplicate data.
> Archive truncate RDS plant_status table.

- plant_health/Dockerfile
- plant_health/main.tf
- plant_health/plant_health_report.py
- plant_health/requirements.txt
- plant_health/variables.tf
Lambda handler for comparing plant metrics to expected values, and returning a json file with the warning data. 
Feel free to discuss metrics used, and range values.
> Lambda handler

- pipeline/ETL-scripts/extract.py
- pipeline/pipeline.py
Definetally useful, and fixes loads of stuff. is currently running on lambda
> fixing stuff for the pipeline

- dashboard/dash_graphs.py
- dashboard/dash_queries.py
- dashboard/dashboard.py
- pipeline/terraform/lambda_pipeline.tf
I add one line to the terraform, dashboard changes
> Dashboard changes and one extra terraform line

- plant_health/plant_health_report.py
The text in the email alerts was updated for the last watered section.
> Updated text in email alerts

- archive/lambda_function/archive_pipeline.py
- archive/lambda_function/logger_config.py
- pipeline/pipeline.py
Added logging to output the successful extraction, transformation and loading of data to the S3, as well as the truncation of the `plant_status` table.
> logging added to archive lambda function

- archive/lambda_function/archive_pipeline.py
- archive/lambda_function/logger_config.py
- archive/lambda_function/test_archive_pipeline.py
- schema/seed_master_data.py
- schema/test_seed_master_data.py
Changes to pipeline and archive pylint. All scores over 7
> Pylint changes
